//global.e = xmlFromString(TestData());
global.e = xmlFromFile("TMC_XML\\test6.xml");
xmlToFile(global.e,"TMC_XML\\testout.xml");

Text = xmlToString(global.e);

show_debug_message("XML:______________")
show_debug_message(Text)
show_debug_message("UTF8:______________")
utf8s = utf8_string_to_utf8(@"
015B ś LATIN SMALL LETTER S WITH ACUTE
015E Ş LATIN CAPITAL LETTER S WITH CEDILLA
015F ş LATIN SMALL LETTER S WITH CEDILLA
0160 Š LATIN CAPITAL LETTER S WITH CARON
0161 š LATIN SMALL LETTER S WITH CARON
0162 Ţ LATIN CAPITAL LETTER T WITH CEDILLA
0163 ţ LATIN SMALL LETTER T WITH CEDILLA
0164 Ť LATIN CAPITAL LETTER T WITH CARON
0165 ť LATIN SMALL LETTER T WITH CARON
016E Ů LATIN CAPITAL LETTER U WITH RING ABOVE
016F ů LATIN SMALL LETTER U WITH RING ABOVE
0170 Ű LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
0171 ű LATIN SMALL LETTER U WITH DOUBLE ACUTE
0178 Ÿ LATIN CAPITAL LETTER Y WITH DIAERESIS
0179 Ź LATIN CAPITAL LETTER Z WITH ACUTE
017A ź LATIN SMALL LETTER Z WITH ACUTE
017B Ż LATIN CAPITAL LETTER Z WITH DOT ABOVE
017C ż LATIN SMALL LETTER Z WITH DOT ABOVE
017D Ž LATIN CAPITAL LETTER Z WITH CARON
017E ž LATIN SMALL LETTER Z WITH CARON
0192 ƒ LATIN SMALL LETTER F WITH HOOK");
show_debug_message(utf8s)
show_debug_message("BACK TO ASCII:______________")
utf8_to_str = utf8_to_string(utf8s);
show_debug_message(utf8_to_str)



